language: cpp

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         wget https://www.cmake.org/files/v3.4/cmake-3.4.1-Linux-x86_64.tar.gz
      && tar -xzf cmake-3.4.1-Linux-x86_64.tar.gz
      && sudo cp -fR cmake-3.4.1-Linux-x86_64/* /usr
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      ;
    fi
        
script:
  - mkdir build
  - cd build
  - cmake ../
  - make
